# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  create-venv:
    cmds:
      - /venv/main/bin/python -m venv --system-site-packages .venv
      - .venv/bin/pip install --upgrade pip
      - .venv/bin/pip install -r requirements.txt
